style_edition = "2024"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
newline_style = "Unix"
error_on_unformatted = false

reorder_modules = true
reorder_imports = true
max_width = 100
tab_spaces = 4 
