name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          cache: false
        
      - name: Install Libaries
        run: sudo apt update;sudo apt install -y libpipewire-0.3-dev clang libdbus-1-dev pkg-config

      - name: Build
        env:
          RUSTFLAGS: "-A dead_code"
        run: cargo build
